"classes/hegrenade.res"
{

	"desp"
	{
		"ControlName"		"Label"
		"fieldName"		"desp"
		"xpos"			"0"
		"ypos"			"128"
		"wide"			"300"
		"tall"			"60"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"HIGH EXPLOSIVE GRENADE \nThe high explosive fragmentation grenade administers high \ndamage through a wide area, making it ideal for clearing out \nhostile rooms.”
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
	}
	"line"
	{
		"ControlName"		"Label"
		"fieldName"		"line"
		"xpos"			"0"
		"ypos"			"170"
		"wide"			"290"
		"tall"			"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"_______________________________________________________"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
	}
	"fields"
	{
		"ControlName"		"Label"
		"fieldName"		"fields"
		"xpos"			"0"
		"ypos"			"29"
		"wide"			"150"
		"tall"			"362"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"PRICE \nUSAGE \nMAX DAMAGE \n\nMOBILITY"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
	}
	"colons"
	{
		"ControlName"		"Label"
		"fieldName"		"colons"
		"xpos"			"130"
		"ypos"			"29"
		"wide"			"10"
		"tall"			"362"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		": \n: \n: \n\n:"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
	}
	"values"
	{
		"ControlName"		"Label"
		"fieldName"		"values"
		"xpos"			"140"
		"ypos"			"29"
		"wide"			"150"
		"tall"			"362"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"$300 \nDealing explosive splash damage \n96 (Unarmored) \n48 (Armored) \n250"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
	}
	"imageBG"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"imageBG"
		"xpos"			"0"
		"ypos"			"0"
		"wide"			"300"
		"tall"			"128"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"		"center"
		"fillColor"		"WindowBG"
	}
	"classimage"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"classimage"
		"xpos"			"0"
		"ypos"			"0"
		"wide"			"300"
		"tall"			"128"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"		"west"
		"image"			"gfx/vgui/hegrenade"
		"scaleImage"		"1"
	}
	"imageBorder"
	{
		"ControlName"		"Divider"
		"fieldName"		"imageBorder"
		"xpos"			"0"
		"ypos"			"0"
		"wide"			"300"
		"tall"			"128"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"zpos"			"2"
	}
}